name: typingapp
description: "Yet another typing app, but for desktop and web usage"
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.8.1

dependencies:
    flutter:
        sdk: flutter
    flutter_riverpod: ^3.0.3
    freezed_annotation: ^3.1.0
    gap: ^3.0.1
    google_fonts: ^6.3.2
    riverpod: ^3.0.3
    riverpod_annotation: ^3.0.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
    riverpod_generator: ^3.0.3
    build_runner: ^2.7.1
    freezed: ^3.2.3

flutter:
    uses-material-design: true
    assets:
        - assets/strings/
